<script lang="ts">
	import {
		Home,
		Dumbbell,
		CalendarDays,
		ChartNoAxesCombined,
		Ellipsis,
		ArrowUpRight,
		ArrowRight,
		Plus,
		ChevronLeft,
		ChevronRight,
		ArrowUp,
		ArrowDown,
		Trash2,
		Check,
		X,
		Timer,
		Play,
		Pause,
		History,
		Settings,
		Upload,
		BookOpen,
		LogOut,
		Search,
		CircleHelp,
		RotateCcw,
		CloudCheck,
		WifiOff,
		Zap,
		Copy,
		Archive,
		Pencil,
		Download,
		CircleAlert,
		Menu,
		Flame,
		MoveRight
	} from '@lucide/svelte';
	let { name, size = 20 }: { name: string; size?: number } = $props();
	const icons: Record<string, typeof Home> = {
		home: Home,
		workouts: Dumbbell,
		calendar: CalendarDays,
		progress: ChartNoAxesCombined,
		more: Ellipsis,
		external: ArrowUpRight,
		arrow: ArrowRight,
		plus: Plus,
		left: ChevronLeft,
		right: ChevronRight,
		up: ArrowUp,
		down: ArrowDown,
		delete: Trash2,
		check: Check,
		close: X,
		timer: Timer,
		play: Play,
		pause: Pause,
		history: History,
		settings: Settings,
		import: Upload,
		book: BookOpen,
		logout: LogOut,
		search: Search,
		help: CircleHelp,
		undo: RotateCcw,
		cloud: CloudCheck,
		offline: WifiOff,
		zap: Zap,
		copy: Copy,
		archive: Archive,
		edit: Pencil,
		download: Download,
		alert: CircleAlert,
		menu: Menu,
		flame: Flame,
		move: MoveRight
	};
	const Glyph = $derived(icons[name] || Dumbbell);
</script>

<Glyph {size} strokeWidth={2} aria-hidden="true" />
